application:
  appId: PY-123
  assetId: PY-123
  sdlcType: EDM
  appType: Webapp
  webservice: false
  restApi: false
  microservice: false
  riskMatrixRevision: Rev1.0
  sourceFilePattern: ".*\\+\\+\\+.*(\\.py)+.*"
  sensitivePackagePattern: ".*(\\+\\+\\+.*(org\\/hdivsamples\\/security)).*"
  fileChangeThreshold: 20

environment:
  bitbucketOwner: sig-devsecops
  bitbucketRepositoryName: InsecureBank
  bitbucketBranchName: master
  testDeploymentRoot: "insecure-bank"
  imChannelIdentifier: "#stargazer-notifications"
  jiraProjectName: "DEM"
  jiraIssuesQuery: "resolution = \"Unresolved\" AND labels in (Security, Defect)"
